services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: sh -c "sleep 3 && make test"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    image: "mavyxz/devops-for-programmers-project-74"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=${DATABASE_NAME-postgres}
      - DATABASE_HOST=${DATABASE_HOST-db}
      - DATABASE_USERNAME=${DATABASE_USERNAME-postgres}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD-password}

  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD-password}
      - POSTGRES_DB=${DATABASE_NAME-postgres}
    volumes:
      - db-data:/var/lib/posgresql/data

volumes:
  db-data:
  node_modules:
