services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: sh -c "make test"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    image: "mavyxz/devops-for-programmers-project-74:${TAG}"

volumes:
  node_modules:
