name: push

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

env:
  TEST_TAG: mavyxz/devops-for-programmers-project-74:test
  LATEST_TAG: mavyxz/devops-for-programmers-project-74:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Environment
        run: |
          cp .env.example .env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.production
          load: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=registry,ref=${{ env.TEST_TAG }}
          cache-to: type=inline

      - name: Test
        run: TAG=test make ci

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.production
          push: true
          tags: ${{ env.LATEST_TAG }}



